### ISSUE TITLE
deprecation roadmap

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-PHAL-plugin-gui-network-client#2]
- [ ] make QML independent from Plasma Network Manager
- [ ] get all needed info / send all wifi commands via https://github.com/OpenVoiceOS/ovos-PHAL-plugin-network-manager
- [ ] move QML files to https://github.com/OpenVoiceOS/ovos-PHAL-plugin-network-manager directly
- [ ] deprecate/archive this plugin
